'use client';

import React from 'react';
import { Button } from '@/components/ui/button';
import { Download, FileText, Share2, Clipboard } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { MarkdownRenderer } from '@/components/markdown-renderer';

interface SmartNotesProps {
    content: string; // The JSON string or parsed object
}

interface NoteData {
    detailed_answer: string;
}

export function SmartNotes({ content }: SmartNotesProps) {
    const { toast } = useToast();
    const [data, setData] = React.useState<NoteData | null>(null);

    React.useEffect(() => {
        try {
            if (typeof content === 'string') {
                setData(JSON.parse(content));
            } else {
                setData(content);
            }
        } catch (e) {
            console.error("Failed to parse Smart Notes JSON", e);
            // Fallback or handle error - though the parent should likely handle this
        }
    }, [content]);

    if (!data) return null;

    const handleDownloadPDF = async () => {
        try {
            // Dynamic import to avoid SSR issues with jsPDF
            const jsPDF = (await import('jspdf')).default;
            const doc = new jsPDF();

            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 10;
            let y = 10;

            // Title & Branding
            doc.setFillColor(63, 81, 181); // Primary color
            doc.rect(0, 0, pageWidth, 20, "F");
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(22);
            doc.setFont("helvetica", "bold");
            doc.text("Smart Notes", margin, 13);
            doc.setFontSize(10);
            doc.text("Generated by DeciMind AI", pageWidth - margin - 40, 13);

            y = 35;
            doc.setTextColor(0, 0, 0);

            // Detailed Answer
            doc.setFontSize(18);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(63, 81, 181);
            doc.text("Detailed Answer", margin, y);
            y += 10;
            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(0, 0, 0);

            // Clean up markdown slightly for PDF
            const cleanAnswer = data.detailed_answer
                .replace(/\*\*(.*?)\*\*/g, '$1') // Remove bold markers
                .replace(/###\s?/g, '') // Remove H3
                .replace(/##\s?/g, '') // Remove H2
                .replace(/#\s?/g, ''); // Remove H1

            const answerLines = doc.splitTextToSize(cleanAnswer, pageWidth - 2 * margin);
            doc.text(answerLines, margin, y);

            // Footer
            const pageCount = doc.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(9);
                doc.setTextColor(150);
                doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, 290);
            }



            doc.save("smart-notes.pdf");
            toast({ title: "PDF Downloaded", description: "Your smart notes have been saved as PDF." });

        } catch (error) {
            console.error("PDF generation failed:", error);
            toast({ title: "Error", description: "Failed to generate PDF.", variant: "destructive" });
        }
    };

    const handleDownloadDOCX = async () => {
        try {
            const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');
            const { saveAs } = await import('file-saver');

            const children = [
                new Paragraph({
                    text: "Smart Notes",
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 100 },
                    run: {
                        color: "3f51b5",
                        bold: true,
                        size: 32,
                    }
                }),
                new Paragraph({
                    text: "Generated by DeciMind AI",
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                    run: {
                        color: "888888",
                        size: 20,
                    }
                }),
                new Paragraph({
                    text: "Detailed Answer",
                    heading: HeadingLevel.HEADING_2,
                    spacing: { after: 200, before: 100 },
                    run: { color: "3f51b5" }
                }),
                ...data.detailed_answer.split('\n').map(line => {
                    // Simple bold parsing for docx
                    const parts = line.split(/(\*\*.*?\*\*)/g);
                    const children = parts.map(part => {
                        if (part.startsWith('**') && part.endsWith('**')) {
                            return new TextRun({ text: part.slice(2, -2), bold: true });
                        }
                        return new TextRun({ text: part });
                    });

                    return new Paragraph({
                        children: children,
                        spacing: { after: 100 }
                    });
                })
            ];

            const doc = new Document({
                sections: [{ children }],
            });

            const blob = await Packer.toBlob(doc);
            saveAs(blob, "smart-notes.docx");
            toast({ title: "DOCX Downloaded", description: "Your smart notes have been saved as Word document." });

        } catch (error) {
            console.error("DOCX generation failed", error);
            toast({ title: "Error", description: "Failed to generate DOCX.", variant: "destructive" });
        }
    };

    const handleCopy = () => {
        let text = `Smart Notes\n\nDetailed Answer:\n${data.detailed_answer}`;
        navigator.clipboard.writeText(text);
        toast({ title: "Copied", description: "Notes copied to clipboard." });
    }

    const handleCopyDetailed = () => {
        navigator.clipboard.writeText(data.detailed_answer);
        toast({ title: "Copied Answer", description: "Detailed answer copied to clipboard." });
    }

    return (
        <div className="space-y-6 w-full max-w-4xl mx-auto bg-card border rounded-xl p-6 shadow-sm">
            <div className="flex flex-wrap items-center justify-between gap-4 border-b pb-4">
                <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-purple-600">Smart Notes</h2>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleCopy} title="Copy to Clipboard">
                        <Clipboard className="h-4 w-4 mr-2" /> Copy
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleDownloadPDF} title="Download PDF">
                        <FileText className="h-4 w-4 mr-2" /> PDF
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleDownloadDOCX} title="Download DOCX">
                        <Download className="h-4 w-4 mr-2" /> DOCX
                    </Button>
                </div>
            </div>

            <div className="grid gap-6">
                <section>
                    <div className="flex items-center justify-between mb-2">
                        <h3 className="text-lg font-semibold text-primary">Detailed Answer</h3>
                        <Button variant="ghost" size="icon" onClick={handleCopyDetailed} title="Copy Answer">
                            <Clipboard className="h-4 w-4" />
                        </Button>
                    </div>
                    <div className="bg-background/80 p-6 rounded-xl border-2 border-primary/10 leading-relaxed text-foreground/90 shadow-sm">
                        <MarkdownRenderer content={data.detailed_answer} />
                    </div>
                </section>
            </div>
        </div>
    );
}
